// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018102531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Kültür Turu"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Doğa Turu"
                        });
                });

            modelBuilder.Entity("Core.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Karadeniz"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Doğa"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Yemek"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Tarih"
                        },
                        new
                        {
                            TagId = 5,
                            Name = "Deniz"
                        });
                });

            modelBuilder.Entity("Core.Entities.Tour", b =>
                {
                    b.Property<long>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TourId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SpecialNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("TourId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            TourId = 1L,
                            CategoryId = 1,
                            CoverImage = "karadeniz_cover.jpg",
                            Description = "Trabzon’dan başlayan ve yaylaları kapsayan doğa ve kültür turu.",
                            Name = "Karadeniz Yayla Turu",
                            SpecialNotes = "Yanınıza mutlaka yağmurluk alın"
                        },
                        new
                        {
                            TourId = 2L,
                            CategoryId = 1,
                            CoverImage = "ege_cover.jpg",
                            Description = "İzmir’den başlayıp Efes ve Bergama antik kentlerini kapsayan kültürel tur.",
                            Name = "Ege Antik Kentler Turu",
                            SpecialNotes = "Güneş kremi ve şapka önerilir"
                        });
                });

            modelBuilder.Entity("Core.Entities.TourCoupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("CouponId");

                    b.HasIndex("TourId", "Code")
                        .IsUnique();

                    b.ToTable("TourCoupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            Code = "KARADENIZ20",
                            DiscountType = "percent",
                            EndDate = new DateTime(2025, 9, 30, 23, 59, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TourId = 1L,
                            Value = 20.00m
                        },
                        new
                        {
                            CouponId = 2,
                            Code = "EGE300",
                            DiscountType = "amount",
                            EndDate = new DateTime(2025, 9, 20, 23, 59, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            TourId = 2L,
                            Value = 300.00m
                        },
                        new
                        {
                            CouponId = 3,
                            Code = "YAYLA150",
                            DiscountType = "amount",
                            EndDate = new DateTime(2025, 9, 25, 23, 59, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TourId = 1L,
                            Value = 150.00m
                        });
                });

            modelBuilder.Entity("Core.Entities.TourCouponUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsageId"));

                    b.Property<int>("CouponId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UsageId");

                    b.HasIndex("CouponId");

                    b.ToTable("TourCouponUsages");

                    b.HasData(
                        new
                        {
                            UsageId = 1,
                            CouponId = 1,
                            UsedAt = new DateTime(2025, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 101L
                        },
                        new
                        {
                            UsageId = 2,
                            CouponId = 1,
                            UsedAt = new DateTime(2025, 9, 7, 15, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 102L
                        },
                        new
                        {
                            UsageId = 3,
                            CouponId = 1,
                            UsedAt = new DateTime(2025, 9, 8, 9, 45, 0, 0, DateTimeKind.Utc),
                            UserId = 103L
                        },
                        new
                        {
                            UsageId = 4,
                            CouponId = 2,
                            UsedAt = new DateTime(2025, 9, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 104L
                        },
                        new
                        {
                            UsageId = 5,
                            CouponId = 2,
                            UsedAt = new DateTime(2025, 9, 13, 11, 20, 0, 0, DateTimeKind.Utc),
                            UserId = 105L
                        },
                        new
                        {
                            UsageId = 6,
                            CouponId = 3,
                            UsedAt = new DateTime(2025, 9, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 106L
                        },
                        new
                        {
                            UsageId = 7,
                            CouponId = 3,
                            UsedAt = new DateTime(2025, 9, 11, 14, 45, 0, 0, DateTimeKind.Utc),
                            UserId = 107L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourExclude", b =>
                {
                    b.Property<int>("ExcludeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ExcludeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("ExcludeId");

                    b.HasIndex("TourId");

                    b.ToTable("TourExcludes");

                    b.HasData(
                        new
                        {
                            ExcludeId = 1,
                            Description = "Kişisel harcamalar",
                            TourId = 1L
                        },
                        new
                        {
                            ExcludeId = 2,
                            Description = "Müze giriş ücretleri",
                            TourId = 1L
                        },
                        new
                        {
                            ExcludeId = 3,
                            Description = "Öğle ve akşam yemekleri",
                            TourId = 2L
                        },
                        new
                        {
                            ExcludeId = 4,
                            Description = "Müze giriş ücretleri",
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourExtraFee", b =>
                {
                    b.Property<int>("ExtraFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ExtraFeeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("ExtraFeeId");

                    b.HasIndex("TourId");

                    b.ToTable("TourExtraFees");

                    b.HasData(
                        new
                        {
                            ExtraFeeId = 1,
                            Amount = 50.00m,
                            Name = "Müze giriş ücreti",
                            TourId = 1L
                        },
                        new
                        {
                            ExtraFeeId = 2,
                            Amount = 100.00m,
                            Name = "Teleferik ücreti",
                            TourId = 1L
                        },
                        new
                        {
                            ExtraFeeId = 3,
                            Amount = 150.00m,
                            Name = "Efes giriş bileti",
                            TourId = 2L
                        },
                        new
                        {
                            ExtraFeeId = 4,
                            Amount = 120.00m,
                            Name = "Bergama Akropol ücreti",
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourHotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("HotelId"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("HotelId");

                    b.HasIndex("TourId");

                    b.ToTable("TourHotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            CheckIn = new DateTime(2025, 9, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            CheckOut = new DateTime(2025, 9, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trabzon merkezde konaklama",
                            Name = "Trabzon Otel",
                            TourId = 1L
                        },
                        new
                        {
                            HotelId = 2,
                            CheckIn = new DateTime(2025, 9, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            CheckOut = new DateTime(2025, 9, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yayla manzaralı konaklama",
                            Name = "Ayder Dağ Evi",
                            TourId = 1L
                        },
                        new
                        {
                            HotelId = 3,
                            CheckIn = new DateTime(2025, 9, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            CheckOut = new DateTime(2025, 9, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İzmir merkezde konaklama",
                            Name = "İzmir City Hotel",
                            TourId = 2L
                        },
                        new
                        {
                            HotelId = 4,
                            CheckIn = new DateTime(2025, 9, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            CheckOut = new DateTime(2025, 9, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deniz kenarında resort otel",
                            Name = "Kuşadası Resort",
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("ImageId"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("ImageId");

                    b.HasIndex("TourId");

                    b.ToTable("TourImages");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            IsCover = true,
                            TourId = 1L,
                            Url = "karadeniz_cover.jpg"
                        },
                        new
                        {
                            ImageId = 2,
                            IsCover = false,
                            TourId = 1L,
                            Url = "karadeniz1.jpg"
                        },
                        new
                        {
                            ImageId = 3,
                            IsCover = false,
                            TourId = 1L,
                            Url = "karadeniz2.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            IsCover = true,
                            TourId = 2L,
                            Url = "ege_cover.jpg"
                        },
                        new
                        {
                            ImageId = 5,
                            IsCover = false,
                            TourId = 2L,
                            Url = "ege1.jpg"
                        },
                        new
                        {
                            ImageId = 6,
                            IsCover = false,
                            TourId = 2L,
                            Url = "ege2.jpg"
                        });
                });

            modelBuilder.Entity("Core.Entities.TourInclude", b =>
                {
                    b.Property<int>("IncludeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("IncludeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("IncludeId");

                    b.HasIndex("TourId");

                    b.ToTable("TourIncludes");

                    b.HasData(
                        new
                        {
                            IncludeId = 1,
                            Description = "Ulaşım",
                            TourId = 1L
                        },
                        new
                        {
                            IncludeId = 2,
                            Description = "Rehberlik hizmeti",
                            TourId = 1L
                        },
                        new
                        {
                            IncludeId = 3,
                            Description = "2 gece otel konaklaması",
                            TourId = 1L
                        },
                        new
                        {
                            IncludeId = 4,
                            Description = "Ulaşım",
                            TourId = 2L
                        },
                        new
                        {
                            IncludeId = 5,
                            Description = "Profesyonel rehber",
                            TourId = 2L
                        },
                        new
                        {
                            IncludeId = 6,
                            Description = "1 gece otel konaklaması",
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourPrice", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("PriceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("PriceId");

                    b.HasIndex("TourId");

                    b.ToTable("TourPrices");

                    b.HasData(
                        new
                        {
                            PriceId = 1,
                            Amount = 2500.00m,
                            PriceType = "Yetişkin",
                            TourId = 1L
                        },
                        new
                        {
                            PriceId = 2,
                            Amount = 2000.00m,
                            PriceType = "Öğrenci",
                            TourId = 1L
                        },
                        new
                        {
                            PriceId = 3,
                            Amount = 1500.00m,
                            PriceType = "Çocuk",
                            TourId = 1L
                        },
                        new
                        {
                            PriceId = 4,
                            Amount = 3000.00m,
                            PriceType = "Yetişkin",
                            TourId = 2L
                        },
                        new
                        {
                            PriceId = 5,
                            Amount = 2500.00m,
                            PriceType = "Öğrenci",
                            TourId = 2L
                        },
                        new
                        {
                            PriceId = 6,
                            Amount = 1800.00m,
                            PriceType = "Çocuk",
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RouteId"));

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("RouteId");

                    b.HasIndex("TourId");

                    b.ToTable("TourRoutes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            ArrivalTime = new TimeOnly(9, 0, 0),
                            LocationName = "Trabzon",
                            OrderNo = 1,
                            TourId = 1L
                        },
                        new
                        {
                            RouteId = 2,
                            ArrivalTime = new TimeOnly(10, 30, 0),
                            LocationName = "Sürmene",
                            OrderNo = 2,
                            TourId = 1L
                        },
                        new
                        {
                            RouteId = 3,
                            ArrivalTime = new TimeOnly(12, 0, 0),
                            LocationName = "Uzungöl",
                            OrderNo = 3,
                            TourId = 1L
                        },
                        new
                        {
                            RouteId = 4,
                            ArrivalTime = new TimeOnly(15, 0, 0),
                            LocationName = "Ayder Yaylası",
                            OrderNo = 4,
                            TourId = 1L
                        },
                        new
                        {
                            RouteId = 5,
                            ArrivalTime = new TimeOnly(8, 0, 0),
                            LocationName = "İzmir",
                            OrderNo = 1,
                            TourId = 2L
                        },
                        new
                        {
                            RouteId = 6,
                            ArrivalTime = new TimeOnly(10, 0, 0),
                            LocationName = "Efes Antik Kenti",
                            OrderNo = 2,
                            TourId = 2L
                        },
                        new
                        {
                            RouteId = 7,
                            ArrivalTime = new TimeOnly(13, 0, 0),
                            LocationName = "Şirince",
                            OrderNo = 3,
                            TourId = 2L
                        },
                        new
                        {
                            RouteId = 8,
                            ArrivalTime = new TimeOnly(16, 0, 0),
                            LocationName = "Bergama",
                            OrderNo = 4,
                            TourId = 2L
                        });
                });

            modelBuilder.Entity("Core.Entities.TourTag", b =>
                {
                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("TourId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TourTags");

                    b.HasData(
                        new
                        {
                            TourId = 1L,
                            TagId = 1
                        },
                        new
                        {
                            TourId = 1L,
                            TagId = 2
                        },
                        new
                        {
                            TourId = 1L,
                            TagId = 3
                        },
                        new
                        {
                            TourId = 2L,
                            TagId = 4
                        },
                        new
                        {
                            TourId = 2L,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Core.Entities.Tour", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Tours")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.TourCoupon", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Coupons")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourCouponUsage", b =>
                {
                    b.HasOne("Core.Entities.TourCoupon", "Coupon")
                        .WithMany("Usages")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("Core.Entities.TourExclude", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Excludes")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourExtraFee", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("ExtraFees")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourHotel", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Hotels")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourImage", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourInclude", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Includes")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourPrice", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Prices")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourRoute", b =>
                {
                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("Routes")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.TourTag", b =>
                {
                    b.HasOne("Core.Entities.Tag", "Tag")
                        .WithMany("TourTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tour", "Tour")
                        .WithMany("TourTags")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Core.Entities.Tag", b =>
                {
                    b.Navigation("TourTags");
                });

            modelBuilder.Entity("Core.Entities.Tour", b =>
                {
                    b.Navigation("Coupons");

                    b.Navigation("Excludes");

                    b.Navigation("ExtraFees");

                    b.Navigation("Hotels");

                    b.Navigation("Images");

                    b.Navigation("Includes");

                    b.Navigation("Prices");

                    b.Navigation("Routes");

                    b.Navigation("TourTags");
                });

            modelBuilder.Entity("Core.Entities.TourCoupon", b =>
                {
                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
